version: "3.9"
networks:
  deploy-dev:
    driver: bridge
services:
  webapp: 
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - deploy-dev
    depends_on:
      - postgres_backend
      
  postgres_backend:
    container_name: postgres_backend
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: upt
    ports:
      - "5432:5432"
    networks:
      - deploy-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: