version: "3.9"
networks:
  deploy-dev:
    driver: bridge
services:
  app: 
    container_name: upt-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - deploy-dev
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: upt
    ports:
      - "5432:5432"
    networks:
      - deploy-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: